//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework___WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Status1 { get; set; }
    }
}
